[workspace]
members = [
    "psbt",
    "cli",
    "fs",
    "."
]
default-members = [
    "psbt",
    "cli",
    "fs",
    "."
]

[workspace.package]
version = "0.11.0-alpha.2"
keywords = ["bitcoin", "lightning", "rgb", "smart-contracts", "lnp-bp"]
categories = ["cryptography::cryptocurrencies"]
authors = ["Dr Maxim Orlovsky <orlovsky@lnp-bp.org>"]
homepage = "https://lnp-bp.org"
repository = "https://github.com/RGB-WG/rgb-wallet"
rust-version = "1.67" # Due to strict encoding library
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
amplify = "4.5.0"
baid58 = "0.4.4"
commit_verify = "0.11.0-beta.1"
strict_encoding = "2.6.1"
strict_types = "1.6.3"
bp-core = "0.11.0-beta.1"
bp-seals = "0.11.0-beta.1"
bp-std = "0.11.0-beta.2"
bp-wallet = "0.11.0-beta.2"
bp-util = "0.11.0-beta.2"
bp-esplora = "0.11.0-beta.1"
descriptors = "0.11.0-beta.1"
psbt = { version = "0.11.0-beta.1", features = ["client-side-validation"] }
rgb-std = { version = "0.11.0-beta.2", features = ["fs"] }
rgb-psbt = { version = "0.11.0-alpha.2", path = "psbt" }
indexmap = "2.0.2"
chrono = "0.4.31"
serde_crate = { package = "serde", version = "1", features = ["derive"] }
serde_yaml = "0.9.19"
log = { version = "0.4", features = ["max_level_trace", "release_max_level_debug"] }

[package]
name = "rgb-runtime"
version.workspace = true
description = "RGB smart contracts wallet runtime"
keywords.workspace = true
categories.workspace = true
readme = "README.md"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "rgb_rt"

[dependencies]
amplify = { workspace = true }
baid58 = { workspace = true }
strict_types = { workspace = true }
bp-core = { workspace = true }
bp-std = { workspace = true }
bp-wallet = { workspace = true, features = ["fs"] }
bp-esplora = { workspace = true, optional = true }
descriptors = { workspace = true }
rgb-std = { workspace = true }
rgb-psbt = { workspace = true }
rgb-persist-fs = { version = "0.11.0-alpha", path = "fs" }
indexmap = { workspace = true }
chrono = { workspace = true }
serde_crate = { workspace = true, optional = true }
serde_yaml = { workspace = true, optional = true }
log = { workspace = true, optional = true }

[features]
default = []
all = ["esplora",  "serde", "log"]
esplora = ["bp-esplora", "bp-wallet/esplora"]
serde = ["serde_crate", "serde_yaml", "bp-std/serde", "bp-wallet/serde",]

[package.metadata.docs.rs]
features = [ "all" ]

[patch.crates-io]
commit_verify = { git = "https://github.com/LNP-BP/client_side_validation", branch = "v0.11" }
bp-consensus = { git = "https://github.com/BP-WG/bp-core", branch = "doubleanchors" }
bp-dbc = { git = "https://github.com/BP-WG/bp-core", branch = "doubleanchors" }
bp-seals = { git = "https://github.com/BP-WG/bp-core", branch = "doubleanchors" }
bp-core = { git = "https://github.com/BP-WG/bp-core", branch = "doubleanchors" }
bp-invoice = { git = "https://github.com/BP-WG/bp-std", branch = "v0.11" }
bp-std = { git = "https://github.com/BP-WG/bp-std", branch = "v0.11" }
descriptors = { git = "https://github.com/BP-WG/bp-std", branch = "v0.11" }
psbt = { git = "https://github.com/BP-WG/bp-std", branch = "v0.11" }
bp-derive = { git = "https://github.com/BP-WG/bp-std", branch = "v0.11" }
bp-wallet = { git = "https://github.com/BP-WG/bp-wallet", branch = "v0.11" }
bp-util = { git = "https://github.com/BP-WG/bp-wallet", branch = "v0.11" }
bp-esplora = { git = "https://github.com/BP-WG/bp-esplora-client", branch = "master" }
aluvm = { git = "https://github.com/AluVM/rust-aluvm", branch = "v0.11" }
rgb-core = { git = "https://github.com/RGB-WG/rgb-core", branch = "canary" }
rgb-std = { git = "https://github.com/RGB-WG/rgb-std", branch = "v0.11" }
rgb-invoice = { git = "https://github.com/RGB-WG/rgb-std", branch = "v0.11" }
