[workspace]
members = [
    "fs",
    ".",
]
default-members = [
    "fs",
    "."
]

[workspace.package]
authors = ["Dr Maxim Orlovsky <orlovsky@lnp-bp.org>"]
homepage = "https://github.com/RGB-WG"
repository = "https://github.com/RGB-WG/rgb-wallet"
rust-version = "1.66" # Due to strict encoding library (caused by GAD)
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
amplify = "4.0.0-beta.19"
baid58 = "0.2.0"
strict_encoding = "2.0.0-rc.3"
strict_types = "1.0.0-beta.5"
rgb-std = { version = "0.10.0-alpha.1", features = ["fs"] }
rgb-wallet = { version = "0.10.0-alpha.1", features = ["fs"] }

[package]
name = "rgb-contracts"
version = "0.10.0-alpha.1"
description = " RGB: scalable & confidential smart contracts for Bitcoin & Lightning network"
keywords = ["bitcoin", "lightning", "rgb", "smart-contracts", "lnp-bp"]
categories = ["cryptography::cryptocurrencies"]
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
readme = "README.md"
exclude = [".github", "std"]

[lib]
name = "rgb"

[[bin]]
name = "rgb"
required-features = ["cli"]

[dependencies]
amplify = { workspace = true }
baid58 = { workspace = true }
strict_types = { workspace = true, features = ["serde"] }
bp-core = "0.10.0-beta.3"
rgb-std = { workspace = true }
rgb-wallet = { workspace = true }
rgb-persist-fs = { version = "0.10.0-alpha.1", path = "fs" }
log = { version = "0.4", features = ["max_level_trace", "release_max_level_debug"], optional = true }
env_logger = "0.10.0"
clap = { version = "4.1.8", features = ["derive", "env"], optional = true }
shellexpand = { version = "3.0.0", optional = true }
serde_yaml = { version = "0.9.19", optional = true }

[features]
default = []
all = ["cli", "log"]
cli = ["clap", "shellexpand", "log", "serde_yaml"]

[package.metadata.docs.rs]
features = [ "all" ]

[patch.crates-io]
rgb-wallet = { git = "https://github.com/RGB-WG/rgb-wallet" }
rgb-std = { git = "https://github.com/RGB-WG/rgb-wallet" }
